name: ShiftlabGenerated

options:
  minimumXcodeGenVersion: 2.37.0
  createIntermediateGroups: true
  groupSortPosition: top
  groupOrdering: 
    - order: [Sources, Resources, Tests, Packages, Products]

settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 13.0
    TARGETED_DEVICE_FAMILY: 1

packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire.git
    from: 5.8.0
  SnapKit:
    url: https://github.com/SnapKit/SnapKit.git
    from: 5.6.0
  RealmSwift:
    url: https://github.com/realm/realm-swift.git
    from: 10.42.3
  Veil:
    url: https://github.com/DanielCardonaRojas/Veil.git
    from: 0.2.0

targets:
  ShiftlabApp:
    type: application
    platform: iOS
    deploymentTarget: 13.0
    info:
      path: Sources/Resources/Generated/Info.generated.plist
      properties:
        CFBundleDevelopmentRegion: $(DEVELOPMENT_LANGUAGE)
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: 6.0
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: ${MARKETING_VERSION}
        CFBundleVersion: ${CURRENT_PROJECT_VERSION}
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
    settings:
      base:
        INFOPLIST_FILE: Sources/Resources/Generated/Info.generated.plist
        PRODUCT_BUNDLE_IDENTIFIER: io.github.alexkamanin.ShiftlabApp
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
    preBuildScripts:
      - script: |
                ${SRCROOT}/BuildTools/Scripts/SwiftLint/swiftlint.sh
        name: SwiftLint
        basedOnDependencyAnalysis: false
    sources:
       - path: Sources
         excludes:
          - "**/.gitkeep"
    dependencies:
        - package: Alamofire
        - package: SnapKit
        - package: RealmSwift
        - package: Veil